services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-disease-api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped
